function [BW,maskedRGBImage,bs,bb] = createMask_final(RGB)
%createMask  Threshold RGB image using auto-generated code from colorThresholder app.
%  [BW,MASKEDRGBIMAGE] = createMask(RGB) thresholds image RGB using
%  auto-generated code from the colorThresholder app. The colorspace and
%  range for each channel of the colorspace were set within the app. The
%  segmentation mask is returned in BW, and a composite of the mask and
%  original RGB images is returned in maskedRGBImage.

% Auto-generated by colorThresholder app on 23-Oct-2019
%------------------------------------------------------


% Convert RGB image to chosen color space

I = rgb2hsv(RGB);

% Define thresholds for channel 1 based on histogram settings
channel1Min = 0.544;
channel1Max = 0.674;

% Define thresholds for channel 2 based on histogram settings
channel2Min = 0.533;
channel2Max = 1.000;

% Define thresholds for channel 3 based on histogram settings
channel3Min = 0.241;
channel3Max = 1.000;

% Create mask based on chosen histogram thresholds
sliderBW = (I(:,:,1) >= channel1Min ) & (I(:,:,1) <= channel1Max) & ...
    (I(:,:,2) >= channel2Min ) & (I(:,:,2) <= channel2Max) & ...
    (I(:,:,3) >= channel3Min ) & (I(:,:,3) <= channel3Max);
BW = sliderBW;
BW = bwareaopen(BW,50);
BW = imclose(BW, strel('disk',5));
BW = bwareafilt(BW,3);
ch = bwconvhull(BW);
reprops = regionprops(ch,'BoundingBox','Orientation');
% angleC = deg2rad(sin(reprops.Orientation));
bb = reprops.BoundingBox;
bs.len = reprops.BoundingBox(4);
bs.wid = reprops.BoundingBox(3);

% correct bs dims
bs_ratio = bs.len/bs.wid;
if bs_ratio<2.1
    bs.wid = round(bs.len/2.2);
    diff = abs(reprops.BoundingBox(3)-bs.wid);
    bb(1) = reprops.BoundingBox(1)+diff;
    bb(3) = bs.wid;
end

II = RGB;
II(repmat(BW,[1 1 3])) = 0;

BW = createMask_carcass(II);
BW = medfilt2(BW,[3,3]);
% Initialize output masked image based on input image.
maskedRGBImage = RGB;

% Set background pixels where BW is false to zero.
maskedRGBImage(repmat(~BW,[1 1 3])) = 0;

end
